from src.models.addresses import AddressModel
from src.models.associations import contractor_address_table
from src.models.contractors import ContractorModel
from src.models.curators import CuratorModel
from src.models.customers import CustomerModel
from src.models.systems import SystemsModel
from src.models.systems_on_address import SystemOnAddressModel
from src.models.technician_contractor import TechnicianModel
from src.models.types_of_works import TypesOfWorksModel
from src.models.users import UserModel
from src.models.works import WorksModel
